[project]
name = "cuber-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=25.4.0",
    "bs4>=0.0.2",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.129.0",
    "requests>=2.32.5",
    "websockets>=16.0",
]
